services:
  db:
    image: postgres:14.17
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fcg_exercise
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgres
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fcg_exercise"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app
    ports:
      - 8080:8080
    depends_on:
      db:
        condition: service_healthy

volumes:
  db: